### ISSUE TITLE
N-bits Encryption Technique

### ISSUE THREAD

**Issue by dolnuea** [jacobpclouse/526-Final-Project#2]
![image](https://user-images.githubusercontent.com/32684258/226085497-0c9c6e81-aae5-4064-9db6-eeedddc5714a.png)
The encryption algorithm from the paper,
![image](https://user-images.githubusercontent.com/32684258/226085528-eaa1dc41-88b9-43af-b2a1-7e547829fa18.png)

**Comment by jacobpclouse** [comment]
implemented
